name         'puppetlabs-tempest'
version      '3.0.0'
author       'StackForge Contributors'
license      'Apache License 2.0'
summary      'Puppet module for OpenStack Tempest'
description  'Installs and configures OpenStack Tempest (Quality Assurance).'
project_page 'https://launchpad.net/puppet-tempest'
source       'https://github.com/stackforge/puppet-tempest'

dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
dependency 'puppetlabs/stdlib', '>=4.0.0 <5.0.0'
dependency 'puppetlabs/vcsrepo', '>=0.1.2 <1.0.0'
